In [1]:
import requests as r
import pandas as pd
import numpy as np

In [9]:
%time

blocks_df = pd.DataFrame(columns=['block_number', 'miner_reward', 'miner', 'coinbase_transfers', 'gas_used', 'gas_price', 'is_megabundle'])
transactions_df = pd.DataFrame(columns=['transaction_hash', 'tx_index', 'bundle_type', 'bundle_index', 'block_number', 'eoa_address', 'to_address', 'gas_used', 'gas_price', 'coinbase_transfer', 'total_miner_reward'])

blocks = r.get('https://blocks.flashbots.net/v1/blocks?limit=1000').json()

for block in blocks['blocks']:
    transactions = block['transactions']
    del block['transactions']
    blocks_df = blocks_df.append(block, ignore_index=True)
    
    for transaction in transactions:
        transactions_df = transactions_df.append(transaction, ignore_index=True)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.05 µs

In [10]:
blocks_df

,block_number,miner_reward,miner,coinbase_transfers,gas_used,gas_price,is_megabundle
0,13733605,4817358330846491,0x1aD91ee08f21bE3dE0BA2ba6918E714dA6B45836,4817358053952731,382319,12600363389,False
1,13733606,6944559176563380,0xB7e390864a90b7b923C9f9310C6F98aafE43F707,6055724292797430,541792,12817758801,False
2,13733609,11059345219770968,0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8,0,1446728,7644384583,False
3,13733610,6785591717742888,0xB7e390864a90b7b923C9f9310C6F98aafE43F707,6785591717742888,280043,24230535016,False
4,13733612,937500000000000,0x2A20380DcA5bC24D052acfbf79ba23e988ad0050,0,93750,10000000000,False
...,...,...,...,...,...,...,...
995,13735336,216634738468156012,0x1aD91ee08f21bE3dE0BA2ba6918E714dA6B45836,22966377921749080,1521149,142415199607,False
996,13735337,14463388783992473,0x829BD824B016326A401d083B33D092293333A830,14055079079684339,353419,40924197012,False
997,13735339,78796928220476366,0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8,0,95351,826388063266,False
998,13735341,23358560416207416,0x0708F87A089a91C65d48721Aa941084648562287,18287564834396301,1704198,13706482706,False
999,13735342,23697896766992157,0x7F101fE45e6649A6fB8F3F8B43ed03D353f2B90c,23226981667772100,869100,27267169217,False

In [11]:
transactions_df

,transaction_hash,tx_index,bundle_type,bundle_index,block_number,eoa_address,to_address,gas_used,gas_price,coinbase_transfer,total_miner_reward
0,0x67b301537f305c80c1ffa0b8d4a52f0574ca906f1b83...,0,rogue,0,13733605,0x9C6dce2EA23ccE6C7C54d4ed66C76b3c42ee57A3,0xd02C260F54997146C9028b2Ac7144b11ce4c20a6,209768,1320,0,276893760
1,0x3bc2c0d45b7d946eebd352351b321c81e24a9d0941e9...,0,flashbots,1,13733605,0x2Ee36E41387f87B7e6f678A86D1e575b23b996F5,0x4d638adb8c07A78655E9Ae88641c4202774e6584,172551,27918459203,4817358053952731,4817358053952731
2,0x0177bae1546fb89535f29c99cbed107fe91708e00b9c...,0,flashbots,0,13733606,0xAe03d6037f6B46Fa17A643413BB6eC1A7be1feE4,0xA58f22e0766B3764376c92915BA545d583c19DBc,200744,21535317466,4323085769562441,4323085769562441
3,0xa19f1ab63ec6054801abd98b87ee3b8781c4a3fc3207...,0,flashbots,1,13733606,0xB2EdDe593ddFcB46B8081AE557C43f5cbCE73295,0xa57Bd00134B2850B2a1c55860c9e9ea100fDd6CF,197498,8772942122,1732638523234989,1732638523234989
4,0xa70c2d94a558d80f5fb4729cb157015129d119ff8274...,0,flashbots,2,13733606,0xfbB018ae51850FA8FC31d1370052fEBd73096Df4,0xA75AF537fB853bb432f6A51D47d70e349fffc6Ba,143550,6191813889,0,888834883765950
...,...,...,...,...,...,...,...,...,...,...,...
5548,0xded04626637649b14ce5f2abe7929ed1c7c15453e33e...,0,flashbots,1,13735342,0x155F64A5C850c42b21023cFA0305B054a76d27f1,0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F,119235,1500000000,0,178852500000000
5549,0x6762300ddc76b048fc37d4b43cefda261711bc980882...,1,flashbots,1,13735342,0x3B25D8E0801df1264a3d3A5f0Bb79BBc292a09fb,0x4d638adb8c07A78655E9Ae88641c4202774e6584,146253,78661722744,11504512936502781,11504512936502781
5550,0xc36f3578398378d5faa963d0e74d6c17fe83701598e9...,0,flashbots,2,13735342,0xe4a95a1D83e7564096ce04E0BA4FF6edEe69c930,0x00000000726422a6fECb4759b44D47E48Cf746aa,94516,9999,0,945065484
5551,0xd56334909f3f8cb034d71ad6898062669401dbadefb5...,1,flashbots,2,13735342,0xE96247eE726D547b7fddF42f201eBc5011909421,0xE592427A0AEce92De3Edee1F18E0157C05861564,194707,1500000000,0,292060500000000
5552,0x9bf977456189ef9a0a52ee69385d86ab6cbc7a7cacfb...,2,flashbots,2,13735342,0xe4a95a1D83e7564096ce04E0BA4FF6edEe69c930,0x00000000726422a6fECb4759b44D47E48Cf746aa,115427,19681954487,2271827806474494,2271828960629067

In [12]:
blocks_df.to_csv('blocks.csv')

In [13]:
transactions_df.to_csv('transactions.csv')